theme: jekyll-theme-minimal
logo: images/profile-pic.png
title: Adish's homepage
description: "<i>“We don't want to focus on the trees (or their leaves) at the expense of the forest.”</i> - <span style='font-family: cursive;'>Douglas R. Hofstadter</span>"
author: Adish Assain
