theme: jekyll-theme-minimal
logo: images/profile-pic.png
title: Adish's homepage
description: Unperturbed. Moisturized. Happy. In My Lane. Focused. Flourishing.
author:
  name: Adish
  profile_picture: profile-pic.png
